apiVersion: v1
kind: Pod
spec:
  containers:
    - name: spark-kubernetes-driver
      resources:
        requests:
          cpu: '1'
          memory: 4000Mi
          ephemeral-storage: 8Gi
        limits:
          cpu: '1'
          memory: 4000Mi
          ephemeral-storage: 8Gi
