apiVersion: v1
kind: Pod
spec:
  containers:
    - name: spark-kubernetes-executor
      resources:
        requests:
          cpu: '1'
          memory: 51814Mi
          ephemeral-storage: 200Gi
        limits:
          cpu: '1'
          memory: 51814Mi
          ephemeral-storage: 200Gi
